import { useState, useCallback, useRef } from 'react'
import P5Sketch from '../../core/p5/P5Sketch'
import PythonCell from '../../components/viz/PythonCell'
import type { LessonMeta } from '../../types'
import type p5 from 'p5'

export const meta: LessonMeta = {
  id: 'classical/kmeans',
  title: 'K-Means Clustering',
  description: 'Unsupervised learning: partition data into K clusters by iteratively assigning points and moving centroids',
  track: 'classical',
  order: 10,
  tags: ['kmeans', 'clustering', 'unsupervised', 'elbow-method'],
}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

function makeRng(seed: number) {
  let s = seed
  return () => {
    s = (s * 16807) % 2147483647
    return s / 2147483647
  }
}

function randn(rng: () => number): number {
  const u1 = rng()
  const u2 = rng()
  return Math.sqrt(-2 * Math.log(u1 || 0.001)) * Math.cos(2 * Math.PI * u2)
}

const CLUSTER_COLORS: [number, number, number][] = [
  [66, 133, 244],
  [234, 67, 53],
  [52, 211, 153],
  [250, 204, 21],
  [168, 85, 247],
  [251, 146, 60],
  [236, 72, 153],
  [34, 211, 238],
  [163, 230, 53],
  [244, 114, 182],
]

/* ------------------------------------------------------------------ */
/* Section 1 — Interactive K-Means                                     */
/* ------------------------------------------------------------------ */

function KMeansInteractiveSketch() {
  const [k, setK] = useState(3)
  const [step, setStep] = useState(0)
  const pointsRef = useRef<{ x: number; y: number }[]>([])
  const [pointCount, setPointCount] = useState(0)
  const [_autoGenerated, setAutoGenerated] = useState(false)

  const generateData = useCallback(() => {
    const rng = makeRng(Date.now() % 100000)
    const pts: { x: number; y: number }[] = []
    const centers = [
      [150, 150], [400, 120], [250, 350],
      [500, 300], [100, 400],
    ]
    for (let c = 0; c < Math.min(k + 1, 5); c++) {
      for (let i = 0; i < 20; i++) {
        pts.push({
          x: centers[c][0] + randn(rng) * 50,
          y: centers[c][1] + randn(rng) * 50,
        })
      }
    }
    pointsRef.current = pts
    setPointCount(pts.length)
    setStep(0)
    setAutoGenerated(true)
  }, [k])

  const sketch = useCallback(
    (p: p5) => {
      const points = pointsRef.current
      let centroids: { x: number; y: number }[] = []
      let assignments: number[] = []
      let currentStep = 0

      function initCentroids() {
        if (points.length === 0) return
        const rng = makeRng(42)
        centroids = []
        // K-means++ initialization
        const idx0 = Math.floor(rng() * points.length)
        centroids.push({ ...points[idx0] })
        for (let c = 1; c < k; c++) {
          const dists = points.map((pt) => {
            let minD = Infinity
            for (const cen of centroids) {
              const d = (pt.x - cen.x) ** 2 + (pt.y - cen.y) ** 2
              if (d < minD) minD = d
            }
            return minD
          })
          const total = dists.reduce((a, b) => a + b, 0)
          let r = rng() * total
          let chosen = 0
          for (let i = 0; i < dists.length; i++) {
            r -= dists[i]
            if (r <= 0) { chosen = i; break }
          }
          centroids.push({ ...points[chosen] })
        }
        assignments = new Array(points.length).fill(0)
      }

      function assignStep() {
        for (let i = 0; i < points.length; i++) {
          let bestD = Infinity
          let bestC = 0
          for (let c = 0; c < centroids.length; c++) {
            const d = (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
            if (d < bestD) { bestD = d; bestC = c }
          }
          assignments[i] = bestC
        }
      }

      function updateStep() {
        for (let c = 0; c < centroids.length; c++) {
          let sx = 0, sy = 0, n = 0
          for (let i = 0; i < points.length; i++) {
            if (assignments[i] === c) { sx += points[i].x; sy += points[i].y; n++ }
          }
          if (n > 0) {
            centroids[c] = { x: sx / n, y: sy / n }
          }
        }
      }

      p.setup = () => {
        const parent = (p as unknown as Record<string, HTMLElement>)._userNode
        const pw = parent ? parent.clientWidth : 700
        p.createCanvas(pw, 450)
        initCentroids()
      }

      p.draw = () => {
        p.background(15, 23, 42)

        if (points.length === 0) {
          p.fill(148, 163, 184)
          p.textSize(14)
          p.textAlign(p.CENTER, p.CENTER)
          p.text('Click "Generate Data" to create sample points, or click on the canvas to add points manually', p.width / 2, p.height / 2)
          return
        }

        // Run steps up to current step
        if (currentStep !== step) {
          initCentroids()
          for (let s = 0; s < step; s++) {
            assignStep()
            updateStep()
          }
          assignStep() // always assign after last update
          currentStep = step
        }

        // Draw Voronoi-ish background if we have centroids and step > 0
        if (step > 0 && centroids.length > 0) {
          const cellSize = 8
          for (let px = 0; px < p.width; px += cellSize) {
            for (let py = 0; py < p.height; py += cellSize) {
              let bestD = Infinity
              let bestC = 0
              for (let c = 0; c < centroids.length; c++) {
                const d = (px - centroids[c].x) ** 2 + (py - centroids[c].y) ** 2
                if (d < bestD) { bestD = d; bestC = c }
              }
              const col = CLUSTER_COLORS[bestC % CLUSTER_COLORS.length]
              p.noStroke()
              p.fill(col[0], col[1], col[2], 20)
              p.rect(px, py, cellSize, cellSize)
            }
          }
        }

        // Draw points
        p.noStroke()
        for (let i = 0; i < points.length; i++) {
          const c = step > 0 ? assignments[i] : 0
          const col = step > 0
            ? CLUSTER_COLORS[c % CLUSTER_COLORS.length]
            : [148, 163, 184] as [number, number, number]
          p.fill(col[0], col[1], col[2], 200)
          p.ellipse(points[i].x, points[i].y, 8, 8)
        }

        // Draw centroids
        if (step > 0) {
          for (let c = 0; c < centroids.length; c++) {
            const col = CLUSTER_COLORS[c % CLUSTER_COLORS.length]
            p.stroke(255)
            p.strokeWeight(2)
            p.fill(col[0], col[1], col[2])
            // Draw as diamond
            const cx = centroids[c].x
            const cy = centroids[c].y
            const s = 10
            p.beginShape()
            p.vertex(cx, cy - s)
            p.vertex(cx + s, cy)
            p.vertex(cx, cy + s)
            p.vertex(cx - s, cy)
            p.endShape(p.CLOSE)
          }
        }

        // Info
        p.noStroke()
        p.fill(226, 232, 240)
        p.textSize(12)
        p.textAlign(p.LEFT, p.TOP)
        p.text(`K = ${k}  |  Step ${step}  |  ${points.length} points`, 10, 10)
        if (step > 0) {
          // Compute inertia
          let inertia = 0
          for (let i = 0; i < points.length; i++) {
            const c = assignments[i]
            if (centroids[c]) {
              inertia += (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
            }
          }
          p.fill(148, 163, 184)
          p.textSize(11)
          p.text(`Inertia: ${inertia.toFixed(0)}`, 10, 28)
        }
      }

      p.mousePressed = () => {
        if (p.mouseX > 0 && p.mouseX < p.width && p.mouseY > 0 && p.mouseY < p.height) {
          points.push({ x: p.mouseX, y: p.mouseY })
          setPointCount(points.length)
          setStep(0)
          currentStep = -1
        }
      }
    },
    [k, step, pointCount],
  )

  return (
    <P5Sketch
      sketch={sketch}
      height={450}
      controls={
        <div className="flex flex-wrap items-center gap-4 text-sm text-gray-300">
          <label className="flex items-center gap-2">
            K:
            <input type="range" min={2} max={8} step={1} value={k}
              onChange={(e) => { setK(parseInt(e.target.value)); setStep(0) }} className="w-28" />
            <span className="w-6 font-mono">{k}</span>
          </label>
          <label className="flex items-center gap-2">
            Step:
            <input type="range" min={0} max={15} step={1} value={step}
              onChange={(e) => setStep(parseInt(e.target.value))} className="w-28" />
            <span className="w-6 font-mono">{step}</span>
          </label>
          <button onClick={generateData}
            className="rounded bg-indigo-600 px-3 py-1 text-white hover:bg-indigo-500 transition-colors">
            Generate Data
          </button>
          <button onClick={() => { pointsRef.current = []; setPointCount(0); setStep(0); setAutoGenerated(false) }}
            className="rounded bg-gray-700 px-3 py-1 text-gray-300 hover:bg-gray-600 transition-colors">
            Clear
          </button>
        </div>
      }
    />
  )
}

/* ------------------------------------------------------------------ */
/* Section 2 — Multiple Initializations                                */
/* ------------------------------------------------------------------ */

function InitializationSketch() {
  const [selectedRun, setSelectedRun] = useState(0)

  const sketch = useCallback(
    (p: p5) => {
      const dataRng = makeRng(99)
      const points: { x: number; y: number }[] = []
      const centers = [[150, 150], [400, 130], [280, 380]]
      for (const [cx, cy] of centers) {
        for (let i = 0; i < 25; i++) {
          points.push({ x: cx + randn(dataRng) * 45, y: cy + randn(dataRng) * 45 })
        }
      }

      const K = 3
      const nRuns = 5

      // Run K-means with different seeds
      function runKmeans(seed: number) {
        const rng = makeRng(seed)
        let centroids = Array.from({ length: K }, () => ({
          x: 50 + rng() * 500, y: 50 + rng() * 380,
        }))
        let assigns = new Array(points.length).fill(0)

        for (let iter = 0; iter < 20; iter++) {
          // Assign
          for (let i = 0; i < points.length; i++) {
            let bestD = Infinity, bestC = 0
            for (let c = 0; c < K; c++) {
              const d = (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
              if (d < bestD) { bestD = d; bestC = c }
            }
            assigns[i] = bestC
          }
          // Update
          const newCentroids = centroids.map(() => ({ x: 0, y: 0, n: 0 }))
          for (let i = 0; i < points.length; i++) {
            newCentroids[assigns[i]].x += points[i].x
            newCentroids[assigns[i]].y += points[i].y
            newCentroids[assigns[i]].n++
          }
          centroids = newCentroids.map((c, idx) =>
            c.n > 0 ? { x: c.x / c.n, y: c.y / c.n } : centroids[idx]
          )
        }

        // Compute inertia
        let inertia = 0
        for (let i = 0; i < points.length; i++) {
          const c = assigns[i]
          inertia += (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
        }
        return { centroids, assigns, inertia }
      }

      const runs = Array.from({ length: nRuns }, (_, i) => runKmeans(i * 137 + 7))

      p.setup = () => {
        const parent = (p as unknown as Record<string, HTMLElement>)._userNode
        const pw = parent ? parent.clientWidth : 700
        p.createCanvas(pw, 430)
      }

      p.draw = () => {
        p.background(15, 23, 42)
        const run = runs[selectedRun]

        // Points
        p.noStroke()
        for (let i = 0; i < points.length; i++) {
          const col = CLUSTER_COLORS[run.assigns[i] % CLUSTER_COLORS.length]
          p.fill(col[0], col[1], col[2], 200)
          p.ellipse(points[i].x, points[i].y, 8, 8)
        }

        // Centroids
        for (let c = 0; c < K; c++) {
          const col = CLUSTER_COLORS[c % CLUSTER_COLORS.length]
          p.stroke(255)
          p.strokeWeight(2)
          p.fill(col[0], col[1], col[2])
          const cx = run.centroids[c].x
          const cy = run.centroids[c].y
          const s = 12
          p.beginShape()
          p.vertex(cx, cy - s)
          p.vertex(cx + s, cy)
          p.vertex(cx, cy + s)
          p.vertex(cx - s, cy)
          p.endShape(p.CLOSE)
        }

        // Info bar at bottom
        const barY = p.height - 40
        const barW = (p.width - 40) / nRuns
        for (let r = 0; r < nRuns; r++) {
          const isSelected = r === selectedRun
          const isBest = runs[r].inertia === Math.min(...runs.map((rn) => rn.inertia))
          p.noStroke()
          p.fill(isSelected ? 99 : 30, isSelected ? 102 : 41, isSelected ? 241 : 59, isSelected ? 200 : 150)
          p.rect(20 + r * barW + 2, barY, barW - 4, 30, 4)
          p.fill(isSelected ? 255 : 180)
          p.textSize(10)
          p.textAlign(p.CENTER, p.CENTER)
          p.text(`Run ${r + 1}: ${runs[r].inertia.toFixed(0)}${isBest ? ' *' : ''}`, 20 + r * barW + barW / 2, barY + 15)
        }

        // Title
        p.noStroke()
        p.fill(226, 232, 240)
        p.textSize(13)
        p.textAlign(p.LEFT, p.TOP)
        p.text(`Run ${selectedRun + 1}  |  Inertia: ${run.inertia.toFixed(0)}`, 10, 10)
        p.fill(148, 163, 184)
        p.textSize(11)
        p.text('* = lowest inertia (best). Different initializations yield different results.', 10, 28)
      }
    },
    [selectedRun],
  )

  return (
    <P5Sketch
      sketch={sketch}
      height={430}
      controls={
        <div className="flex items-center gap-4 text-sm text-gray-300">
          <label className="flex items-center gap-2">
            Run:
            <input type="range" min={0} max={4} step={1} value={selectedRun}
              onChange={(e) => setSelectedRun(parseInt(e.target.value))} className="w-36" />
            <span className="w-10 font-mono">Run {selectedRun + 1}</span>
          </label>
        </div>
      }
    />
  )
}

/* ------------------------------------------------------------------ */
/* Section 3 — Elbow Method                                            */
/* ------------------------------------------------------------------ */

function ElbowMethodSketch() {
  const sketch = useCallback((p: p5) => {
    const dataRng = makeRng(55)
    const points: { x: number; y: number }[] = []
    const trueCenters = [[2, 5], [5, 2], [8, 6], [6, 8]]
    for (const [cx, cy] of trueCenters) {
      for (let i = 0; i < 30; i++) {
        points.push({ x: cx + randn(dataRng) * 0.8, y: cy + randn(dataRng) * 0.8 })
      }
    }

    function runKmeans(kVal: number, seed: number) {
      const rng = makeRng(seed)
      let centroids = Array.from({ length: kVal }, () => ({
        x: rng() * 10, y: rng() * 10,
      }))
      let assigns = new Array(points.length).fill(0)

      for (let iter = 0; iter < 30; iter++) {
        for (let i = 0; i < points.length; i++) {
          let bestD = Infinity, bestC = 0
          for (let c = 0; c < kVal; c++) {
            const d = (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
            if (d < bestD) { bestD = d; bestC = c }
          }
          assigns[i] = bestC
        }
        const newCentroids = centroids.map(() => ({ x: 0, y: 0, n: 0 }))
        for (let i = 0; i < points.length; i++) {
          newCentroids[assigns[i]].x += points[i].x
          newCentroids[assigns[i]].y += points[i].y
          newCentroids[assigns[i]].n++
        }
        centroids = newCentroids.map((c, idx) =>
          c.n > 0 ? { x: c.x / c.n, y: c.y / c.n } : centroids[idx]
        )
      }

      let inertia = 0
      for (let i = 0; i < points.length; i++) {
        const c = assigns[i]
        inertia += (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
      }
      return inertia
    }

    const ks = Array.from({ length: 10 }, (_, i) => i + 1)
    const inertias = ks.map((kVal) => {
      // Run 3 times, take best
      const results = [runKmeans(kVal, 42), runKmeans(kVal, 99), runKmeans(kVal, 137)]
      return Math.min(...results)
    })

    let animFrame = 0

    p.setup = () => {
      const parent = (p as unknown as Record<string, HTMLElement>)._userNode
      const pw = parent ? parent.clientWidth : 700
      p.createCanvas(pw, 350)
      animFrame = 0
    }

    p.draw = () => {
      p.background(15, 23, 42)
      animFrame++
      const visibleK = Math.min(10, Math.floor(animFrame / 15) + 1)

      const margin = 60
      const plotW = p.width - margin * 2
      const plotH = p.height - margin * 2
      const maxInertia = inertias[0] * 1.1

      function mx(kVal: number): number { return margin + ((kVal - 1) / 9) * plotW }
      function my(val: number): number { return p.height - margin - (val / maxInertia) * plotH }

      // Axes
      p.stroke(51, 65, 85)
      p.strokeWeight(1)
      p.line(margin, p.height - margin, p.width - margin, p.height - margin)
      p.line(margin, margin, margin, p.height - margin)

      // Labels
      p.noStroke()
      p.fill(148, 163, 184)
      p.textSize(12)
      p.textAlign(p.CENTER, p.TOP)
      p.text('Number of Clusters (K)', p.width / 2, p.height - 18)
      p.push()
      p.translate(16, p.height / 2)
      p.rotate(-p.HALF_PI)
      p.textAlign(p.CENTER, p.BOTTOM)
      p.text('Inertia (Sum of Squared Distances)', 0, 0)
      p.pop()

      // Tick marks
      p.textSize(10)
      p.textAlign(p.CENTER, p.TOP)
      for (let kVal = 1; kVal <= 10; kVal++) {
        p.fill(100, 116, 139)
        p.text(kVal.toString(), mx(kVal), p.height - margin + 6)
      }

      // Curve
      p.noFill()
      p.stroke(99, 102, 241)
      p.strokeWeight(2)
      p.beginShape()
      for (let i = 0; i < visibleK; i++) {
        p.vertex(mx(ks[i]), my(inertias[i]))
      }
      p.endShape()

      // Points
      p.noStroke()
      for (let i = 0; i < visibleK; i++) {
        p.fill(99, 102, 241)
        p.ellipse(mx(ks[i]), my(inertias[i]), 8, 8)
      }

      // Elbow highlight at K=4
      if (visibleK >= 4) {
        p.stroke(250, 204, 21, 180)
        p.strokeWeight(1.5)
        ;(p.drawingContext as CanvasRenderingContext2D).setLineDash([5, 5])
        p.line(mx(4), margin, mx(4), p.height - margin)
        ;(p.drawingContext as CanvasRenderingContext2D).setLineDash([])

        p.noStroke()
        p.fill(250, 204, 21)
        p.textSize(12)
        p.textAlign(p.CENTER, p.TOP)
        p.text('Elbow (K=4)', mx(4), margin - 4)
      }

      // Title
      p.noStroke()
      p.fill(226, 232, 240)
      p.textSize(13)
      p.textAlign(p.LEFT, p.TOP)
      p.text('Elbow Method', margin, 6)
    }
  }, [])

  return <P5Sketch sketch={sketch} height={350} />
}

/* ------------------------------------------------------------------ */
/* Section 4 — K-Means Failures                                        */
/* ------------------------------------------------------------------ */

function KMeansFailuresSketch() {
  const [dataset, setDataset] = useState<'moons' | 'sizes' | 'rings'>('moons')

  const sketch = useCallback(
    (p: p5) => {
      const rng = makeRng(42)
      const points: { x: number; y: number; trueLabel: number }[] = []

      if (dataset === 'moons') {
        // Two interleaving half-moons
        for (let i = 0; i < 80; i++) {
          const t = (i / 80) * Math.PI
          points.push({
            x: 250 + Math.cos(t) * 120 + randn(rng) * 12,
            y: 220 - Math.sin(t) * 120 + randn(rng) * 12,
            trueLabel: 0,
          })
          points.push({
            x: 350 - Math.cos(t) * 120 + randn(rng) * 12,
            y: 260 + Math.sin(t) * 120 + randn(rng) * 12,
            trueLabel: 1,
          })
        }
      } else if (dataset === 'sizes') {
        // One big cluster, one small
        for (let i = 0; i < 120; i++) {
          points.push({
            x: 200 + randn(rng) * 80, y: 220 + randn(rng) * 80, trueLabel: 0,
          })
        }
        for (let i = 0; i < 20; i++) {
          points.push({
            x: 480 + randn(rng) * 20, y: 220 + randn(rng) * 20, trueLabel: 1,
          })
        }
      } else {
        // Concentric rings
        for (let i = 0; i < 80; i++) {
          const angle = rng() * Math.PI * 2
          const r1 = 40 + randn(rng) * 8
          points.push({
            x: 300 + Math.cos(angle) * r1, y: 220 + Math.sin(angle) * r1, trueLabel: 0,
          })
          const r2 = 130 + randn(rng) * 10
          points.push({
            x: 300 + Math.cos(angle + 0.5) * r2, y: 220 + Math.sin(angle + 0.5) * r2, trueLabel: 1,
          })
        }
      }

      // Run K-means with K=2
      const K = 2
      function runKM() {
        const kmRng = makeRng(77)
        let centroids = Array.from({ length: K }, () => ({
          x: 100 + kmRng() * 400, y: 100 + kmRng() * 280,
        }))
        const assigns = new Array(points.length).fill(0)
        for (let iter = 0; iter < 30; iter++) {
          for (let i = 0; i < points.length; i++) {
            let bestD = Infinity, bestC = 0
            for (let c = 0; c < K; c++) {
              const d = (points[i].x - centroids[c].x) ** 2 + (points[i].y - centroids[c].y) ** 2
              if (d < bestD) { bestD = d; bestC = c }
            }
            assigns[i] = bestC
          }
          const nc = centroids.map(() => ({ x: 0, y: 0, n: 0 }))
          for (let i = 0; i < points.length; i++) {
            nc[assigns[i]].x += points[i].x
            nc[assigns[i]].y += points[i].y
            nc[assigns[i]].n++
          }
          centroids = nc.map((c, idx) => c.n > 0 ? { x: c.x / c.n, y: c.y / c.n } : centroids[idx])
        }
        return { assigns, centroids }
      }

      const { assigns, centroids } = runKM()

      p.setup = () => {
        const parent = (p as unknown as Record<string, HTMLElement>)._userNode
        const pw = parent ? parent.clientWidth : 700
        p.createCanvas(pw, 440)
      }

      p.draw = () => {
        p.background(15, 23, 42)

        // Left: true labels
        const halfW = p.width / 2 - 20
        p.noStroke()
        p.fill(226, 232, 240)
        p.textSize(12)
        p.textAlign(p.CENTER, p.TOP)
        p.text('True Labels', halfW / 2, 8)

        for (const pt of points) {
          const col = CLUSTER_COLORS[pt.trueLabel]
          p.fill(col[0], col[1], col[2], 200)
          p.noStroke()
          const offsetX = (pt.x / 600) * halfW
          const offsetY = pt.y
          p.ellipse(offsetX, offsetY, 7, 7)
        }

        // Divider
        p.stroke(51, 65, 85)
        p.strokeWeight(1)
        p.line(p.width / 2, 30, p.width / 2, p.height - 10)

        // Right: K-means result
        p.noStroke()
        p.fill(226, 232, 240)
        p.textSize(12)
        p.textAlign(p.CENTER, p.TOP)
        p.text('K-Means Result (K=2)', p.width / 2 + halfW / 2 + 10, 8)

        for (let i = 0; i < points.length; i++) {
          const col = CLUSTER_COLORS[assigns[i]]
          p.fill(col[0], col[1], col[2], 200)
          p.noStroke()
          const offsetX = p.width / 2 + 10 + (points[i].x / 600) * halfW
          p.ellipse(offsetX, points[i].y, 7, 7)
        }

        // Centroids on right side
        for (let c = 0; c < K; c++) {
          const col = CLUSTER_COLORS[c]
          p.stroke(255)
          p.strokeWeight(2)
          p.fill(col[0], col[1], col[2])
          const cx = p.width / 2 + 10 + (centroids[c].x / 600) * halfW
          const cy = centroids[c].y
          const s = 10
          p.beginShape()
          p.vertex(cx, cy - s)
          p.vertex(cx + s, cy)
          p.vertex(cx, cy + s)
          p.vertex(cx - s, cy)
          p.endShape(p.CLOSE)
        }

        // Bottom label
        p.noStroke()
        p.fill(234, 67, 53)
        p.textSize(11)
        p.textAlign(p.CENTER, p.BOTTOM)
        p.text('K-Means fails: clusters are not spherical / equal-sized', p.width / 2, p.height - 5)
      }
    },
    [dataset],
  )

  return (
    <P5Sketch
      sketch={sketch}
      height={440}
      controls={
        <div className="flex items-center gap-4 text-sm text-gray-300">
          {(['moons', 'sizes', 'rings'] as const).map((ds) => (
            <button key={ds} onClick={() => setDataset(ds)}
              className={`rounded px-3 py-1 transition-colors ${dataset === ds ? 'bg-indigo-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}>
              {ds === 'moons' ? 'Half-Moons' : ds === 'sizes' ? 'Unequal Sizes' : 'Concentric Rings'}
            </button>
          ))}
        </div>
      }
    />
  )
}

/* ------------------------------------------------------------------ */
/* Main Lesson Component                                              */
/* ------------------------------------------------------------------ */

export default function KMeans() {
  return (
    <article className="mx-auto max-w-4xl space-y-16 px-4 py-10 text-gray-200">
      {/* ---------- Section 1: Unsupervised Learning ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">1. Unsupervised Learning</h2>
        <p className="mb-4 text-gray-300">
          Everything we have studied so far — linear regression, logistic regression, SVMs, decision
          trees — belongs to <strong className="text-white">supervised learning</strong>. In
          supervised learning, every training example comes with a label (the "answer"), and the
          model learns a mapping from inputs to those labels.
        </p>
        <p className="mb-4 text-gray-300">
          <strong className="text-white">Unsupervised learning</strong> operates without labels. The
          model receives only the input features X and must discover hidden structure on its own. The
          most common task is <strong className="text-white">clustering</strong>: grouping similar
          data points together. Other unsupervised tasks include dimensionality reduction (PCA,
          t-SNE), anomaly detection, and density estimation.
        </p>
        <p className="mb-4 text-gray-300">
          Clustering is useful in many real-world scenarios: customer segmentation, document
          grouping, image compression, gene expression analysis, and anomaly detection. The
          challenge is that without labels, there is no single "correct" answer — the quality of
          clustering depends on domain knowledge and the choice of algorithm.
        </p>
      </section>

      {/* ---------- Section 2: K-Means Algorithm ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">2. The K-Means Algorithm</h2>
        <p className="mb-4 text-gray-300">
          K-Means is the simplest and most widely used clustering algorithm. It partitions N data
          points into exactly K clusters, where each point belongs to the cluster with the nearest
          centroid (center of mass).
        </p>
        <h3 className="mb-2 text-lg font-semibold text-white">The algorithm in 3 steps</h3>
        <ol className="mb-4 list-decimal pl-6 space-y-1 text-gray-300">
          <li><strong className="text-white">Initialize:</strong> Place K centroids at random positions (or use K-means++ for smarter placement).</li>
          <li><strong className="text-white">Assign:</strong> For each point, find the nearest centroid and assign the point to that cluster.</li>
          <li><strong className="text-white">Update:</strong> Move each centroid to the mean of all points assigned to it.</li>
        </ol>
        <p className="mb-4 text-gray-300">
          Repeat steps 2-3 until centroids stop moving (convergence). K-Means is guaranteed to
          converge because each step decreases the total inertia (sum of squared distances from
          points to their assigned centroids), and there are finitely many possible assignments.
        </p>
        <p className="mb-6 text-gray-300">
          Click "Generate Data" to create sample points, or click directly on the canvas to place
          points manually. Then use the Step slider to advance the algorithm one iteration at a time.
          Watch the centroids (diamonds) move and the Voronoi regions recolor.
        </p>
        <KMeansInteractiveSketch />
      </section>

      {/* ---------- Section 3: Initialization Matters ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">3. Initialization Matters</h2>
        <p className="mb-4 text-gray-300">
          K-Means only finds a <strong className="text-white">local optimum</strong>, not the global
          one. This means the final clustering depends heavily on where the centroids start. Two
          different random initializations can produce very different results, with different inertia
          values.
        </p>
        <p className="mb-4 text-gray-300">
          The standard fix is to run K-Means multiple times with different random seeds and keep the
          result with the lowest inertia. Scikit-learn does this by default (n_init=10). A smarter
          approach is <strong className="text-white">K-Means++</strong> initialization: instead of
          placing all centroids randomly, it places the first centroid randomly and then selects each
          subsequent centroid with probability proportional to its squared distance from the nearest
          existing centroid. This spreads centroids apart and almost always produces better results.
        </p>
        <p className="mb-6 text-gray-300">
          Use the slider below to compare 5 different random initializations on the same data. Notice
          how inertia varies. The run marked with * has the lowest inertia and would be selected as
          the best.
        </p>
        <InitializationSketch />
      </section>

      {/* ---------- Section 4: Elbow Method ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">4. The Elbow Method</h2>
        <p className="mb-4 text-gray-300">
          The biggest question in K-Means is: <em>how do you choose K?</em> There is no single
          correct answer, but the <strong className="text-white">elbow method</strong> provides a
          useful heuristic. Plot the inertia (total within-cluster sum of squared distances) for
          K = 1, 2, 3, ..., and look for the "elbow" — the point where increasing K gives
          diminishing returns.
        </p>
        <p className="mb-4 text-gray-300">
          Before the elbow, adding a cluster significantly reduces inertia because it splits a
          genuinely distinct group. After the elbow, adding clusters merely subdivides existing
          groups with little benefit. The data below has 4 true clusters, and the elbow appears at
          K=4.
        </p>
        <ElbowMethodSketch />
      </section>

      {/* ---------- Section 5: Silhouette Score ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">5. Silhouette Score</h2>
        <p className="mb-4 text-gray-300">
          The <strong className="text-white">silhouette score</strong> provides a more principled way
          to evaluate clustering quality. For each point i, it computes:
        </p>
        <div className="mb-4 rounded-lg border border-gray-700 bg-gray-800/50 p-4 font-mono text-sm text-gray-300">
          <p>a(i) = mean distance from i to other points in the same cluster</p>
          <p>b(i) = mean distance from i to points in the nearest different cluster</p>
          <p>s(i) = (b(i) - a(i)) / max(a(i), b(i))</p>
        </div>
        <p className="mb-4 text-gray-300">
          The silhouette score ranges from -1 to 1. A score near <strong className="text-white">+1</strong> means
          the point is well inside its own cluster and far from other clusters.
          A score near <strong className="text-white">0</strong> means the point is on the boundary between
          clusters. A score near <strong className="text-white">-1</strong> means the point is likely assigned
          to the wrong cluster.
        </p>
        <p className="mb-4 text-gray-300">
          The average silhouette score across all points summarizes clustering quality. Compare this
          metric across different values of K: the K with the highest average silhouette is often
          the best choice. Unlike the elbow method, the silhouette score gives an absolute measure
          of quality, not a relative one.
        </p>
      </section>

      {/* ---------- Section 6: Limitations ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">6. When K-Means Fails</h2>
        <p className="mb-4 text-gray-300">
          K-Means assumes clusters are <strong className="text-white">spherical</strong> (isotropic),
          <strong className="text-white"> equally sized</strong>, and <strong className="text-white">
          equally dense</strong>. When these assumptions are violated, K-Means produces poor
          results. Three classic failure modes are shown below:
        </p>
        <ul className="mb-4 list-disc pl-6 space-y-1 text-gray-300">
          <li><strong className="text-white">Half-Moons:</strong> Two interleaving crescent shapes. K-Means splits them vertically instead of following the curved boundary.</li>
          <li><strong className="text-white">Unequal Sizes:</strong> One large and one small cluster. K-Means steals points from the small cluster to balance sizes.</li>
          <li><strong className="text-white">Concentric Rings:</strong> Two rings at different radii. K-Means cannot separate them because they share the same center.</li>
        </ul>
        <p className="mb-6 text-gray-300">
          For non-spherical clusters, consider DBSCAN (density-based), spectral clustering
          (graph-based), or Gaussian Mixture Models (which handle elliptical clusters). Toggle
          between the three failure datasets below.
        </p>
        <KMeansFailuresSketch />
      </section>

      {/* ---------- Section 7: Python - K-Means from Scratch ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">7. Python: K-Means from Scratch</h2>
        <p className="mb-4 text-gray-300">
          Implementing K-Means from scratch is straightforward with NumPy. The core loop alternates
          between assigning each point to its nearest centroid and updating centroids to the mean of
          their assigned points.
        </p>
        <PythonCell
          defaultCode={`import numpy as np

# Generate 3-cluster data
rng = np.random.RandomState(42)
centers = np.array([[2, 2], [6, 6], [2, 8]])
X = np.vstack([rng.randn(50, 2) * 0.8 + c for c in centers])

# K-Means from scratch
K = 3
# Random initialization
idx = rng.choice(len(X), K, replace=False)
centroids = X[idx].copy()

for iteration in range(20):
    # Assign: compute distances from each point to each centroid
    dists = np.linalg.norm(X[:, None] - centroids[None, :], axis=2)  # (N, K)
    labels = np.argmin(dists, axis=1)

    # Update: move centroids to cluster means
    new_centroids = np.array([X[labels == k].mean(axis=0) if (labels == k).any() else centroids[k]
                              for k in range(K)])

    # Check convergence
    shift = np.linalg.norm(new_centroids - centroids)
    centroids = new_centroids
    if shift < 1e-4:
        print(f"Converged at iteration {iteration}")
        break

# Results
inertia = sum(np.sum((X[labels == k] - centroids[k])**2) for k in range(K))
print(f"Inertia: {inertia:.2f}")
for k in range(K):
    print(f"Cluster {k}: {(labels == k).sum()} points, centroid = ({centroids[k][0]:.2f}, {centroids[k][1]:.2f})")

# Now with sklearn (equivalent)
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3, random_state=42, n_init=10).fit(X)
print(f"\\nsklearn inertia: {km.inertia_:.2f}")
`}
        />
      </section>

      {/* ---------- Section 8: Python - Elbow + Silhouette ---------- */}
      <section>
        <h2 className="mb-3 text-2xl font-bold text-white">8. Python: Elbow Method & Silhouette Analysis</h2>
        <p className="mb-4 text-gray-300">
          Use scikit-learn to compute inertia and silhouette scores for different values of K. The
          elbow in the inertia curve and the peak in the silhouette score both point to the optimal K.
        </p>
        <PythonCell
          defaultCode={`import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.datasets import make_blobs

# Generate data with 4 true clusters
X, y_true = make_blobs(n_samples=300, centers=4, cluster_std=0.8, random_state=42)

# Evaluate K = 2 to 8
print(f"{'K':>3} | {'Inertia':>10} | {'Silhouette':>10}")
print("-" * 30)

best_sil = -1
best_k = 2

for k in range(2, 9):
    km = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X)
    sil = silhouette_score(X, km.labels_)
    print(f"{k:>3} | {km.inertia_:>10.1f} | {sil:>10.3f}")

    if sil > best_sil:
        best_sil = sil
        best_k = k

print(f"\\nBest K by silhouette score: {best_k} (score = {best_sil:.3f})")
print(f"True number of clusters: {len(set(y_true))}")

# Adjusted Rand Index - measure agreement with true labels
from sklearn.metrics import adjusted_rand_score
km_best = KMeans(n_clusters=best_k, random_state=42, n_init=10).fit(X)
ari = adjusted_rand_score(y_true, km_best.labels_)
print(f"Adjusted Rand Index (vs true labels): {ari:.3f}")
`}
        />
      </section>
    </article>
  )
}
